#simple IOS config in ansible
---
- name: Sample IOS config for Ansible 2.5
  hosts: iosxe
  gather_facts: no

  tasks:

  - name: Delete loopback {{pod_number}}
    ios_interface:
      name: Loopback{{pod_number}}
      state: absent


